### PR TITLE
Fix Naive Bayes feature_counts modified when p_feature_given_class is calculated

### PR DESCRIPTION
**Pull request by d-me-tree**
`MultinomialNB` calculates incorrect conditional probabilities when given **new, unseen** features.

NOTE: only `MultinomialNB` is affected by this bug (as it's the only model that uses `n_terms`. However, I updated `BernoulliNB` and `ComplementNB` for consistency.

Here's an example:
```python
import math

from creme import compose
from creme import feature_extraction
from creme import naive_bayes

docs = [
    ('cloudy cold', 0),
    ('sunny warm', 1),

]

model = compose.Pipeline([
    ('tokenize', feature_extraction.BoW()),
    ('nb', naive_bayes.MultinomialNB(alpha=1))
])

for sentence, label in docs:
    model = model.fit_one(sentence, label)

# Predict
text = 'new word'
tokens = model['tokenize'].transform_one(text)

# P(1|new word)
#   = P(new|1) * P(word|1) * P(1)
#   ∝ (N_new_1 + 1) / (N_1 + n_terms) * (N_word_1 + 1) / (N_1 + n_terms) * P(1)
p_new_1 = (0 + 1) / (2 + 4)
p_word_1 = (0 + 1) / (2 + 4)

posterior_1 = p_new_1 * p_word_1 * (1/2)


p_new_0 = (0 + 1) / (2 + 4)
p_word_0 = (0 + 1) / (2 + 4)

posterior_0 = p_new_0 * p_word_0 * (1/2)

# Expect two posteriors to be equal
print(posterior_0, posterior_0, posterior_0 == posterior_1)  # 0.013888888888888888 0.013888888888888888 True
print(math.log(posterior_0))  # -4.276666119016055

jll = model['nb'].joint_log_likelihood(tokens)  # {1: -4.718498871295095, 0: -4.852030263919617}
# Expect jll[0] == jll[1] == math.log(posterior_0)
print(jll, jll[0] == jll[1])  # {1: -4.718498871295095, 0: -4.852030263919617}, False

# Calculate jll again
jll = model['nb'].joint_log_likelihood(tokens)
print(model['nb'].joint_log_likelihood(tokens))  # {0: -4.852030263919617, 1: -4.852030263919617}

# Now jll[0] == jll[1] BUT jil[0] < math.log(posterior_0)
print(jll[0] == jll[1], jll[0] == math.log(posterior_0), jll[0] < math.log(posterior_0))  # True False True
```

The bug comes from using `[]` on `collections.defaultdict(collections.Counter)` instead of `get()`. When getting an unseen word (the only place this happens is when calculating `num` in `p_feature_given_class` method), this word gets inserted into the `feature_counts`, affecting `n_terms` property.

### CODE REVIEW

**Comment by MaxHalford** [comment]
Hey there. Nice catch! Travis is failing for a stupid file encoding bug which I will fix soon. 

Ideally you could add a unit test with the example you're giving. Would adding a unit test bother you?

**Comment by d-me-tree** [comment]
Hey Max! Thank you for the prompt reply.
I ran tests before, and I got the same error as on Travis.

Sure, I'll write a unit test for it. This is my first time contributing to an open-source project. Please let me know if there's anything else I've missed.

**Comment by MaxHalford** [comment]
Yeah don't worry. As long as your tests run correctly locally it's okay. It's great to know this is your first contribution!

**Comment by d-me-tree** [comment]
That's the thing - I couldn't get the tests to work. I'm seeing the same
error as on Travis.

I still will be able to run the unit test, but I'd also like to run all the
test locally too to insure I didn't break anything inadvertently.

**Comment by MaxHalford** [comment]
Even when you run `pytest creme/naive_bayes`?

**Comment by d-me-tree** [comment]
I was able to run `pytest creme/naive_bayes` locally.

I've now added tests. Let me know if there's anything else you think I need to add or change.

**Comment by MaxHalford** [comment]
The tests are beautiful, you rock!

**Pull request merged**
