### PR TITLE
Fixed readme links

### PR DESCRIPTION
**Pull request by greatsharma**

### CODE REVIEW

**Comment by greatsharma** [comment]
@MaxHalford why it is showing `0 contributors` in [https://github.com/creme-ml/creme/blob/master/creme/optim/nadam.py](here)

**Comment by MaxHalford** [comment]
I just fixed the links actually!

**Comment by greatsharma** [comment]
why it is showing `0 contributors` in `nadam.py`

> I just fixed the links actually!



> I just fixed the links actually!

why it is showing `0 contributors` in `nadam.py` ?

**Comment by MaxHalford** [comment]
I think you need to give GitHub some time :)

**Comment by greatsharma** [comment]
> I think you need to give GitHub some time :)

For the first time it took so long to update. But finally it's done. Thank you for merging my code :)

**Pull request closed without merging**
